var R=require("../../../../chunks/ssr/[turbopack]_runtime.js")("server/app/(app)/assistants/[id]/page.js")
R.c("server/chunks/ssr/apps_dashboard_1fnghjy._.js")
R.c("server/chunks/ssr/[root-of-the-server]__06t6j0q._.js")
R.c("server/chunks/ssr/[root-of-the-server]__1b3lf58._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0-0gi_-._.js")
R.c("server/chunks/ssr/apps_dashboard_src_0-mwr_y._.js")
R.c("server/chunks/ssr/1tpz_next_dist_client_components_1k8vpef._.js")
R.c("server/chunks/ssr/1tpz_next_dist_client_components_builtin_forbidden_1clddkt.js")
R.c("server/chunks/ssr/1tpz_next_dist_client_components_builtin_unauthorized_1idko32.js")
R.c("server/chunks/ssr/1tpz_next_dist_client_components_builtin_global-error_17osmth.js")
R.c("server/chunks/ssr/apps_dashboard_src_10y61y1._.js")
R.c("server/chunks/ssr/044u_dashboard__next-internal_server_app_(app)_assistants_[id]_page_actions_0g7n_ky.js")
R.m(82402)
module.exports=R.m(82402).exports
