var R=require("../../../../chunks/ssr/[turbopack]_runtime.js")("server/app/admin/orgs/[id]/page.js")
R.c("server/chunks/ssr/apps_dashboard_0pk9fxl._.js")
R.c("server/chunks/ssr/[root-of-the-server]__06t6j0q._.js")
R.c("server/chunks/ssr/[root-of-the-server]__1b3lf58._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0-0gi_-._.js")
R.c("server/chunks/ssr/apps_dashboard_src_0-mwr_y._.js")
R.c("server/chunks/ssr/1tpz_next_dist_client_components_1k8vpef._.js")
R.c("server/chunks/ssr/1tpz_next_dist_client_components_builtin_forbidden_1clddkt.js")
R.c("server/chunks/ssr/1tpz_next_dist_client_components_builtin_unauthorized_1idko32.js")
R.c("server/chunks/ssr/1tpz_next_dist_client_components_builtin_global-error_17osmth.js")
R.c("server/chunks/ssr/apps_dashboard_src_1xkn5va._.js")
R.c("server/chunks/ssr/apps_dashboard__next-internal_server_app_admin_orgs_[id]_page_actions_0l7mlyj.js")
R.m(78027)
module.exports=R.m(78027).exports
