import type { FastifyInstance } from 'fastify';
import { z } from 'zod';
import { newId } from '../auth/crypto.ts';
import { clientIp } from '../auth/authenticate.ts';
import type { AppContext } from '../context.ts';
import { ApiError } from '../http/errors.ts';
import { cursorClause, idParam, iso, pageRequest, parse, toPage } from '../http/validation.ts';
import { audit } from '../services/audit.ts';
import { decryptWebhookSecret, signWebhook, WEBHOOK_EVENTS, backoffMs } from '../services/webhooks.ts';
import { scope } from './org.ts';

const endpointSchema = z.object({ scopeType: z.enum(['org', 'phone', 'assistant', 'call']).default('org'), scopeId: z.string().uuid().nullable().optional(), url: z.string().url().refine((value) => value.startsWith('https://'), 'Webhook URL must use https'), headers: z.record(z.string().max(1000)).default({}), secret: z.string().min(16).max(4096), events: z.array(z.enum(WEBHOOK_EVENTS)).min(1).default([...WEBHOOK_EVENTS]), transcriptOptIn: z.boolean().default(false), enabled: z.boolean().default(true) }).strict();
const patchSchema = endpointSchema.omit({ secret: true }).partial().extend({ secret: z.string().min(16).max(4096).optional() }).strict();
interface EndpointRow { id: string; cursor_ts: string; org_id: string; scope_type: 'org' | 'phone' | 'assistant' | 'call'; scope_id: string | null; url: string; headers: Record<string, string>; secret_encrypted: any; events: string[]; transcript_opt_in: boolean; enabled: boolean; created_at: Date; updated_at: Date; }
interface DeliveryRow { id: string; cursor_ts: string; endpoint_id: string; call_id: string | null; sequence: number; event_type: string; payload: Record<string, unknown>; status: string; attempts: number; next_attempt_at: Date; response_status: number | null; last_error: string | null; delivered_at: Date | null; created_at: Date; }
const ENDPOINT_COLUMNS = 'id, created_at::text AS cursor_ts, org_id, scope_type, scope_id, url, headers, secret_encrypted, events, transcript_opt_in, enabled, created_at, updated_at';
const DELIVERY_COLUMNS = 'id, created_at::text AS cursor_ts, endpoint_id, call_id, sequence, event_type, payload, status, attempts, next_attempt_at, response_status, last_error, delivered_at, created_at';

const endpointView = (row: EndpointRow) => ({ id: row.id, scopeType: row.scope_type, scopeId: row.scope_id, url: row.url, headers: row.headers, events: row.events, transcriptOptIn: row.transcript_opt_in, enabled: row.enabled, createdAt: iso(row.created_at), updatedAt: iso(row.updated_at) });
const deliveryView = (row: DeliveryRow) => ({ id: row.id, endpointId: row.endpoint_id, callId: row.call_id, sequence: row.sequence, eventType: row.event_type, status: row.status, attempts: row.attempts, nextAttemptAt: iso(row.next_attempt_at), responseStatus: row.response_status, lastError: row.last_error, deliveredAt: iso(row.delivered_at), createdAt: iso(row.created_at) });

export function registerWebhookRoutes(app: FastifyInstance, ctx: AppContext): void {
  app.post('/v1/webhooks', { config: { permission: 'org:update' } }, async (request, reply) => {
    const org = scope(request); const body = parse(endpointSchema, request.body); if (!ctx.toolCipher) throw new ApiError('not_configured', 'Webhook secrets require CREDENTIALS_ENCRYPTION_KEY');
    if (body.scopeType !== 'org' && !body.scopeId) throw new ApiError('validation_error', 'scopeId is required for non-org webhooks', { issues: [{ path: 'scopeId', message: 'Required' }] });
    const id = newId(); const encrypted = ctx.toolCipher.encrypt(body.secret, `${org.id}:webhook:${id}:secret`);
    const row = await org.run(async (tx) => { await tx.query('INSERT INTO webhook_endpoint (id,org_id,scope_type,scope_id,url,headers,secret_encrypted,events,transcript_opt_in,enabled) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10)', [id, org.id, body.scopeType, body.scopeId ?? null, body.url, JSON.stringify(body.headers), JSON.stringify(encrypted), body.events, body.transcriptOptIn, body.enabled]); await audit(tx, { orgId: org.id, actor: org.actor, action: 'webhook.created', targetType: 'webhook', targetId: id, metadata: { scopeType: body.scopeType, scopeId: body.scopeId }, ip: clientIp(request) }); return (await tx.query<EndpointRow>(`SELECT ${ENDPOINT_COLUMNS} FROM webhook_endpoint WHERE org_id=$1 AND id=$2`, [org.id, id])).rows[0]; });
    return reply.code(201).send(endpointView(row));
  });
  app.get('/v1/webhooks', { config: { permission: 'org:read' } }, async (request) => { const org = scope(request); const page = pageRequest(request.query); const cursor = cursorClause(page, 3); const rows = await org.run(async (tx) => (await tx.query<EndpointRow>(`SELECT ${ENDPOINT_COLUMNS} FROM webhook_endpoint WHERE org_id=$1${cursor.sql} ORDER BY created_at DESC,id DESC LIMIT $2`, [org.id, page.limit + 1, ...cursor.params])).rows); return toPage(rows, page.limit, endpointView); });
  app.patch('/v1/webhooks/:id', { config: { permission: 'org:update' } }, async (request) => { const org = scope(request); const id = idParam(request.params, 'id', 'Webhook'); const patch = parse(patchSchema, request.body); const row = await org.run(async (tx) => { const current = (await tx.query<EndpointRow>(`SELECT ${ENDPOINT_COLUMNS} FROM webhook_endpoint WHERE org_id=$1 AND id=$2 FOR UPDATE`, [org.id, id])).rows[0]; if (!current) throw new ApiError('not_found', 'Webhook not found'); const encrypted = patch.secret && ctx.toolCipher ? ctx.toolCipher.encrypt(patch.secret, `${org.id}:webhook:${id}:secret`) : current.secret_encrypted; await tx.query('UPDATE webhook_endpoint SET scope_type=$3,scope_id=$4,url=$5,headers=$6,secret_encrypted=$7,events=$8,transcript_opt_in=$9,enabled=$10,updated_at=now() WHERE org_id=$1 AND id=$2', [org.id, id, patch.scopeType ?? current.scope_type, patch.scopeId === undefined ? current.scope_id : patch.scopeId, patch.url ?? current.url, JSON.stringify(patch.headers ?? current.headers), JSON.stringify(encrypted), patch.events ?? current.events, patch.transcriptOptIn ?? current.transcript_opt_in, patch.enabled ?? current.enabled]); return (await tx.query<EndpointRow>(`SELECT ${ENDPOINT_COLUMNS} FROM webhook_endpoint WHERE org_id=$1 AND id=$2`, [org.id, id])).rows[0]; }); return endpointView(row); });
  app.delete('/v1/webhooks/:id', { config: { permission: 'org:update' } }, async (request, reply) => { const org = scope(request); const id = idParam(request.params, 'id', 'Webhook'); await org.run(async (tx) => { const result = await tx.query('DELETE FROM webhook_endpoint WHERE org_id=$1 AND id=$2', [org.id, id]); if (!result.rowCount) throw new ApiError('not_found', 'Webhook not found'); }); return reply.code(204).send(); });
  app.get('/v1/webhook-deliveries', { config: { permission: 'org:read' } }, async (request) => { const org = scope(request); const page = pageRequest(request.query); const cursor = cursorClause(page, 3); const rows = await org.run(async (tx) => (await tx.query<DeliveryRow>(`SELECT ${DELIVERY_COLUMNS} FROM webhook_delivery WHERE org_id=$1${cursor.sql} ORDER BY created_at DESC,id DESC LIMIT $2`, [org.id, page.limit + 1, ...cursor.params])).rows); return toPage(rows, page.limit, deliveryView); });
  app.post('/v1/webhook-deliveries/:id/redeliver', { config: { permission: 'org:update' } }, async (request) => { const org = scope(request); const id = idParam(request.params, 'id', 'Webhook delivery'); const result = await org.run(async (tx) => { const delivery = (await tx.query<DeliveryRow>(`SELECT ${DELIVERY_COLUMNS} FROM webhook_delivery WHERE org_id=$1 AND id=$2`, [org.id, id])).rows[0]; if (!delivery) throw new ApiError('not_found', 'Webhook delivery not found'); const endpoint = (await tx.query<EndpointRow>(`SELECT ${ENDPOINT_COLUMNS} FROM webhook_endpoint WHERE org_id=$1 AND id=$2`, [org.id, delivery.endpoint_id])).rows[0]; if (!endpoint) throw new ApiError('not_found', 'Webhook endpoint not found'); const secret = ctx.toolCipher ? decryptWebhookSecret(ctx.toolCipher, endpoint.secret_encrypted, org.id, endpoint.id) : ''; const payload = JSON.stringify(delivery.payload); const controller = new AbortController(); const timer = setTimeout(() => controller.abort(), 10_000); try { const response = await ctx.fetch(endpoint.url, { method: 'POST', headers: { 'content-type': 'application/json', ...endpoint.headers, 'x-octo-signature': signWebhook(secret, Math.floor(Date.now() / 1000), payload), 'x-octo-event': delivery.event_type }, body: payload, signal: controller.signal }); const status = response.ok ? 'succeeded' : (delivery.attempts >= 5 ? 'dead' : 'failed'); await tx.query('UPDATE webhook_delivery SET status=$3,attempts=attempts+1,response_status=$4,last_error=$5,delivered_at=CASE WHEN $3=\'succeeded\' THEN now() ELSE delivered_at END,next_attempt_at=now()+($6::text || \' milliseconds\')::interval WHERE org_id=$1 AND id=$2', [org.id, id, status, response.status, response.ok ? null : `HTTP ${response.status}`, backoffMs(delivery.attempts + 1)]); return { status }; } catch (error) { await tx.query('UPDATE webhook_delivery SET status=$3,attempts=attempts+1,last_error=$4,next_attempt_at=now()+($5::text || \' milliseconds\')::interval WHERE org_id=$1 AND id=$2', [org.id, id, delivery.attempts >= 5 ? 'dead' : 'failed', error instanceof Error ? error.message : 'delivery failed', backoffMs(delivery.attempts + 1)]); return { status: delivery.attempts >= 5 ? 'dead' : 'failed' }; } finally { clearTimeout(timer); } }); return result; });
}