// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/admin" | "/admin/orgs" | "/admin/orgs/[id]" | "/admin/users" | "/assistants" | "/assistants/[id]" | "/assistants/new" | "/calls" | "/calls/[id]" | "/catalogs" | "/catalogs/[id]" | "/forgot-password" | "/invite" | "/knowledge" | "/knowledge/[id]" | "/login" | "/reset-password" | "/signup" | "/verify-email"
type PageRoutes = never
type LayoutRoutes = "/" | "/admin"
type RedirectRoutes = never
type RewriteRoutes = "/v1/[[...path]]"
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes


interface ParamMap {
  "/": {}
  "/admin": {}
  "/admin/orgs": {}
  "/admin/orgs/[id]": { "id": string; }
  "/admin/users": {}
  "/assistants": {}
  "/assistants/[id]": { "id": string; }
  "/assistants/new": {}
  "/calls": {}
  "/calls/[id]": { "id": string; }
  "/catalogs": {}
  "/catalogs/[id]": { "id": string; }
  "/forgot-password": {}
  "/invite": {}
  "/knowledge": {}
  "/knowledge/[id]": { "id": string; }
  "/login": {}
  "/reset-password": {}
  "/signup": {}
  "/v1/[[...path]]": { "path"?: string[]; }
  "/verify-email": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/admin": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }
}
