var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/(app)/catalogs/page.js")
R.c("server/chunks/ssr/apps_dashboard_0iombwg._.js")
R.c("server/chunks/ssr/[root-of-the-server]__06t6j0q._.js")
R.c("server/chunks/ssr/[root-of-the-server]__1b3lf58._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0-0gi_-._.js")
R.c("server/chunks/ssr/apps_dashboard_src_0-mwr_y._.js")
R.c("server/chunks/ssr/1tpz_next_dist_client_components_1k8vpef._.js")
R.c("server/chunks/ssr/1tpz_next_dist_client_components_builtin_forbidden_1clddkt.js")
R.c("server/chunks/ssr/1tpz_next_dist_client_components_builtin_unauthorized_1idko32.js")
R.c("server/chunks/ssr/1tpz_next_dist_client_components_builtin_global-error_17osmth.js")
R.c("server/chunks/ssr/apps_dashboard_src_10y61y1._.js")
R.c("server/chunks/ssr/apps_dashboard__next-internal_server_app_(app)_catalogs_page_actions_20tyrcq.js")
R.m(66971)
module.exports=R.m(66971).exports
